# Broadcasting

NumPy’s broadcasting semantics

```
# Broadcasting rules:
# 1. If the dimensions of two arrays are not equal, the smaller array is 'padded' with ones from the left.
# 2. If one of the dimensions of the smaller array is 1, it is stretched to match the other array.
# 3. Arrays must be compatible in all dimensions for broadcasting to work.

```

In [4]:
# Broadcasting Semantics with NumPy
import numpy as np

# Title: Introduction to Broadcasting Semantics
# Broadcasting allows NumPy to perform element-wise operations on arrays of different shapes. 
# It is one of the most powerful features of NumPy because it eliminates the need to duplicate data.

# Example 1: Adding a scalar to an array
# The scalar value is 'broadcast' to each element of the array
array = np.array([1, 2, 3])
scalar = 10
print("Array:", array)
print("Scalar:", scalar)
result = array + scalar  # Broadcasting scalar to each element in the array
print("Result of adding scalar to array:", result)

Array: [1 2 3]
Scalar: 10
Result of adding scalar to array: [11 12 13]


In [5]:
# Example 2: Adding two arrays of different shapes
# NumPy allows operations between arrays of different shapes by broadcasting the smaller array.
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([1, 2, 3])
print("\nMatrix:\n", matrix)
print("Vector:", vector)
# Broadcasting the vector to the matrix
result = matrix + vector
print("Result of broadcasting vector to matrix:\n", result)


Matrix:
 [[1 2 3]
 [4 5 6]]
Vector: [1 2 3]
Result of broadcasting vector to matrix:
 [[2 4 6]
 [5 7 9]]


In [6]:
# Example 3: Broadcasting across higher dimensions
# When one of the arrays has fewer dimensions, it is 'stretched' to match the shape of the larger array.
tensor = np.array([[[1], [2], [3]], [[4], [5], [6]]])  # Shape (2, 3, 1)
array_2d = np.array([[10, 20, 30]])  # Shape (1, 3)

print("\nTensor (3D array):\n", tensor)
print("2D Array:\n", array_2d)

# Broadcasting the 2D array to the 3D tensor
result = tensor + array_2d
print("Result of broadcasting 2D array to 3D tensor:\n", result)




Tensor (3D array):
 [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
2D Array:
 [[10 20 30]]
Result of broadcasting 2D array to 3D tensor:
 [[[11 21 31]
  [12 22 32]
  [13 23 33]]

 [[14 24 34]
  [15 25 35]
  [16 26 36]]]
